import './App.css';
import { useState,useEffect } from 'react';

function App() {
  const examples = [
    "Hunt and peck (two-fingered typing), also known as Eagle Finger, is a common form of typing in which the typist presses each key individually. Instead of relying on the memorized position of keys, the typist must find each key by sight. Use of this method may also prevent the typist from being able to see what has been typed without glancing away from the keys. Although good accuracy may be achieved, any typing errors that are made may not be noticed immediately due to the user not looking at the screen. There is also the disadvantage that because fewer fingers are used, those that are used are forced to move a much greater distance.",
    "Stimulate your mind as you test your typing speed with this standard English paragraph typing test. Watch your typing speed and accuracy increase as you learn about a variety of new topics! Over 40 typing test selections available. If you don't like a test prompt, you can get a different (random) prompt with the 'change test' button - or select a specific paragraph to type from the list below. To find out how fast you type, just start typing in the blank textbox on the right of the test prompt. You will see your progress, including errors on the left side as you type. In order to complete the test and save your score, you need to get 100% accuracy. You can fix errors as you go, or correct them at the end with the help of the spell checker.",
    "Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no variableness, neither shadow of turning. Of his own will begat he us with the word of truth, that we should be a kind of firstfruits of his creatures. Wherefore, my beloved brethren, let every man be swift to hear, slow to speak, slow to wrath: For the wrath of man worketh not the righteousness of God. Wherefore lay apart all filthiness and superfluity of naughtiness, and receive with meekness the engrafted word, which is able to save your souls. But be ye doers of the word, and not hearers only, deceiving your own selves. For if any be a hearer of the word, and not a doer, he is like unto a man beholding his natural face in a glass: For he beholdeth himself, and goeth his way, and straightway forgetteth what manner of man he was. But whoso looketh into the perfect law of liberty, and continueth therein, he being not a forgetful hearer, but a doer of the work, this man shall be blessed in his deed. If any man among you seem to be religious, and bridleth not his tongue, but deceiveth his own heart, this man's religion is vain. Pure religion and undefiled before God and the Father is this, To visit the fatherless and widows in their affliction, and to keep himself unspotted from the world. James 1:17-27",
    "The Mole had been working very hard all the morning, spring-cleaning his little home. First with brooms, then with dusters; then on ladders and steps and chairs, with a brush and a pail of whitewash; till he had dust in his throat and eyes, and splashes of whitewash all over his black fur, and an aching back and weary arms. Spring was moving in the air above and in the earth below and around him, penetrating even his dark and lowly little house with its spirit of divine discontent and longing. It was small wonder, then, that he suddenly flung down his brush on the floor, said ‘Bother!' and ‘O blow!' and also ‘Hang spring-cleaning!' and bolted out of the house without even waiting to put on his coat. Something up above was calling him imperiously, and he made for the steep little tunnel which answered in his case to the gravelled carriage-drive owned by animals whose residences are nearer to the sun and air. So he scraped and scratched and scrabbled and scrooged and then he scrooged again and scrabbled and scratched and scraped, working busily with his little paws and muttering to himself, ‘Up we go! Up we go!' till at last, pop! his snout came out into the sunlight, and he found himself rolling in the warm grass of a great meadow. ('The Wind in the Willows' by Kenneth Grahame)",
    "3 May. Bistritz. - Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning; should have arrived at 6:46, but train was an hour late. Buda-Pesth seems a wonderful place, from the glimpse which I got of it from the train and the little I could walk through the streets. I feared to go very far from the station, as we had arrived late and would start as near the correct time as possible. The impression I had was that we were leaving the West and entering the East; the most western of splendid bridges over the Danube, which is here of noble width and depth, took us among the traditions of Turkish rule. We left in pretty good time, and came after nightfall to Klausenburgh. Here I stopped for the night at the Hotel Royale. I had for dinner, or rather supper, a chicken done up some way with red pepper, which was very good but thirsty. (Mem., get recipe for Mina.) I asked the waiter, and he said it was called 'paprika hendl,' and that, as it was a national dish, I should be able to get it anywhere along the Carpathians. I found my smattering of German very useful here; indeed, I don't know how I should be able to get on without it. ('Dracula' by Bram Stoker)",
    "The rural opinion about the new young ladies, even among the cottagers, was generally in favor of Celia, as being so amiable and innocent-looking, while Miss Brooke's large eyes seemed, like her religion, too unusual and striking. Poor Dorothea! compared with her, the innocent-looking Celia was knowing and worldly-wise; so much subtler is a human mind than the outside tissues which make a sort of blazonry or clock-face for it. Yet those who approached Dorothea, though prejudiced against her by this alarming hearsay, found that she had a charm unaccountably reconcilable with it. Most men thought her bewitching when she was on horseback. She loved the fresh air and the various aspects of the country, and when her eyes and cheeks glowed with mingled pleasure she looked very little like a devotee. Riding was an indulgence which she allowed herself in spite of conscientious qualms; she felt that she enjoyed it in a pagan sensuous way, and always looked forward to renouncing it. ('Middlemarch' by George Eliot)",
    "Mrs. Rachel Lynde lived just where the Avonlea main road dipped down into a little hollow, fringed with alders and ladies' eardrops and traversed by a brook that had its source away back in the woods of the old Cuthbert place; it was reputed to be an intricate, headlong brook in its earlier course through those woods, with dark secrets of pool and cascade; but by the time it reached Lynde's Hollow it was a quiet, well-conducted little stream, for not even a brook could run past Mrs. Rachel Lynde's door without due regard for decency and decorum; it probably was conscious that Mrs. Rachel was sitting at her window, keeping a sharp eye on everything that passed, from brooks and children up, and that if she noticed anything odd or out of place she would never rest until she had ferreted out the whys and wherefores thereof. There are plenty of people in Avonlea and out of it, who can attend closely to their neighbor's business by dint of neglecting their own; but Mrs. Rachel Lynde was one of those capable creatures who can manage their own concerns and those of other folks into the bargain. She was a notable housewife; her work was always done and well done; she 'ran' the Sewing Circle, helped run the Sunday-school, and was the strongest prop of the Church Aid Society and Foreign Missions Auxiliary. ('Anne of Green Gables' by Lucy Maud Montgomery)",
    "I am a very old man; how old I do not know. Possibly I am a hundred, possibly more; but I cannot tell because I have never aged as other men, nor do I remember any childhood. So far as I can recollect I have always been a man, a man of about thirty. I appear today as I did forty years and more ago, and yet I feel that I cannot go on living forever; that some day I shall die the real death from which there is no resurrection. I do not know why I should fear death, I who have died twice and am still alive; but yet I have the same horror of it as you who have never died, and it is because of this terror of death, I believe, that I am so convinced of my mortality. ('A Princess of Mars' by Edgar Rice Burroughs)",
    "Merciful Heavens! but what do I care for the laws of nature and arithmetic, when, for some reason I dislike those laws and the fact that twice two makes four? Of course I cannot break through the wall by battering my head against it if I really have not the strength to knock it down, but I am not going to be reconciled to it simply because it is a stone wall and I have not the strength. ('Notes from the Underground' by Fyodor Dostoyevsky)",
    "In short, his wits being quite gone, he hit upon the strangest notion that ever madman in this world hit upon, and that was that he fancied it was right and requisite, as well for the support of his own honour as for the service of his country, that he should make a knight-errant of himself, roaming the world over in full armour and on horseback in quest of adventures, and putting in practice himself all that he had read of as being the usual practices of knights-errant; righting every kind of wrong, and exposing himself to peril and danger from which, in the issue, he was to reap eternal renown and fame. Already the poor man saw himself crowned by the might of his arm Emperor of Trebizond at least; and so, led away by the intense enjoyment he found in these pleasant fancies, he set himself forthwith to put his scheme into execution. ('Don Quixote' by Miguel de Cervantes Saavedra)",
    "Advertising increased dramatically in the United States as industrialization expanded the supply of manufactured products. In 1919 it was 2.5 percent of Gross Domestic Product (GDP) in the US, and it averaged 2.2 percent of GDP between then and at least 2007, though it may have declined dramatically since the Great Recession. Industry could not benefit from its increased productivity without a substantial increase in consumer spending. This contributed to the development of mass marketing designed to influence the population's economic behavior on a larger scale. In the 1910s and 1920s, advertisers in the U.S. adopted the doctrine that human instincts could be targeted and harnessed - 'sublimated' into the desire to purchase commodities. Edward Bernays, a nephew of Sigmund Freud, became associated with the method and is sometimes called the founder of modern advertising and public relations.",
    'Bernays claimed that: "[The] general principle, that men are very largely actuated by motives which they conceal from themselves, is as true of mass as of individual psychology. It is evident that the successful propagandist must understand the true motives and not be content to accept the reasons which men give for what they do." In other words, selling products by appealing to the rational minds of customers (the main method used prior to Bernays) was much less effective than selling products based on the unconscious desires that Bernays felt were the true motivators of human action. "Sex sells" became a controversial issue, with techniques for titillating and enlarging the audience posing a challenge to conventional morality.',
    "The role of analytical CRM systems is to analyze customer data collected through multiple sources, and present it so that business managers can make more informed decisions. Analytical CRM systems use techniques such as data mining, correlation, and pattern recognition to analyze the customer data. These analytics help improve customer service by finding small problems which can be solved, perhaps, by marketing to different parts of a consumer audience differently. For example, through the analysis of a customer base's buying behavior, a company might see that this customer base has not been buying a lot of products recently. After scanning through this data, the company might think to market to this subset of consumers differently, in order to best communicate how this company's products might benefit this group specifically.",
    'Many businesses are operated through a separate entity such as a corporation or a partnership (either formed with or without limited liability). Most legal jurisdictions allow people to organize such an entity by filing certain charter documents with the relevant Secretary of State or equivalent and complying with certain other ongoing obligations. The relationships and legal rights of shareholders, limited partners, or members are governed partly by the charter documents and partly by the law of the jurisdiction where the entity is organized. Generally speaking, shareholders in a corporation, limited partners in a limited partnership, and members in a limited liability company are shielded from personal liability for the debts and obligations of the entity, which is legally treated as a separate "person". This means that unless there is misconduct, the owner',
    "The Associated Press Stylebook and Briefing on Media Law, usually called the AP Stylebook, is an English grammar style and usage guide created by American journalists working for or connected with the Associated Press over the last century to standardize mass communications. Although it is sold as a guide for reporters, it has become the leading reference for most forms of public-facing corporate communication over the last half-century. The Stylebook offers a basic reference to grammar, punctuation and principles of reporting, including many definitions and rules for usage as well as styles for capitalization, abbreviation, spelling and numerals. The first publicly available edition of the book was published in 1953 and was updated biennially over the next 20 years. While nearly two million copies of the AP Stylebook have been distributed since 1977, today the AP Stylebook is developing an online presence with profiles on social media platforms like Twitter (@APStylebook) and Facebook, and is available through an online subscription model as well as an iOS mobile app.",
    "Brand management is a function of marketing that uses special techniques in order to increase the perceived value of a product. Brand management is the process of identifying the core value of a particular brand and reflecting the core value among the targeted customers. In modern terms, brand could be corporate, product, service, or person. Brand management build brand credibility and credible brands only can build brand loyalty, bounce back from circumstantial crisis, and can benefit from price-sensitive customers. Based on the aims of the established marketing strategy, brand management enables the price of products to grow and builds loyal customers through positive associations and images or a strong awareness of the brand.",
    "Limited liability companies (LLC), limited liability partnerships, and other specific types of business organization protect their owners or shareholders from business failure by doing business under a separate legal entity with certain legal protections. In contrast, unincorporated businesses or persons working on their own are usually not as protected. Corporation: The owners of a corporation have limited liability and the business has a separate legal personality from its owners. Corporations can be either government-owned or privately owned. They can organize either for profit or as nonprofit organizations. A privately owned, for-profit corporation is owned by its shareholders, who elect a board of directors to direct the corporation and hire its managerial staff. A privately owned, for-profit corporation can be either privately held by a small group of individuals, or publicly held, with publicly traded shares listed on a stock exchange.",
    "Businesses serve as conductors of economic activity, and are prevalent in capitalist economies, where most of them are privately owned and provide goods and services allocated through a market to consumers and customers in exchange for other goods, services, money, or other forms of exchange that hold intrinsic economic value. Businesses may also be social nonprofit enterprises or state-owned public enterprises operated by governments with specific social and economic objectives.",
    "Arrested Development is an American television sitcom created by Mitchell Hurwitz, which originally aired on Fox for three seasons from November 2, 2003, to February 10, 2006. The show follows the fictitious Bluth family, a formerly wealthy and habitually dysfunctional family. It is presented in a serialized format, incorporating handheld camera work and voice-over narration, as well as the use of occasional archival photos and historical footage. The show also maintains numerous running gags and catchphrases throughout each season, and the series as a whole. Ron Howard serves as both an executive producer and the series' uncredited omniscient narrator. Set in Newport Beach, California, Arrested Development was filmed primarily in Culver City and Marina del Rey.",
    "Mad Men is an American period drama television series created by Matthew Weiner and produced by Lionsgate Television. The series premiered on July 19, 2007, on the cable network AMC. After seven seasons and 92 episodes, Mad Men's final episode aired on May 17, 2015. Mad Men is set primarily in the 1960s - initially at the fictional Sterling Cooper advertising agency on Madison Avenue in New York City; later at the newly created firm, Sterling Cooper Draper Pryce (later Sterling Cooper & Partners) - located near the Time-Life Building, at 1271 Sixth Avenue. According to the show's pilot, the phrase 'Mad men' was a slang term coined in the 1950s by advertisers working on Madison Avenue to refer to themselves, a claim that has since been disputed. The plot focuses on the business of the agencies as well as the personal lives of the characters, regularly depicting the changing moods and social mores of the United States through the 1960s.",
    "The series begins in March 1960 with season one and moves through November 1970 by the conclusion of season seven. Don Draper (Jon Hamm) is a main focus in the series, initially as the talented creative director at Sterling Cooper and later a founding partner at Sterling Cooper Draper Pryce, as are the people in his personal and professional lives. Throughout its run, Mad Men received widespread critical acclaim for its writing, acting, directing, visual style, and historical authenticity; it has won many awards, including 16 Emmys and five Golden Globes. The show was also the first basic cable series to receive the Emmy Award for Outstanding Drama Series, winning in each of its first four seasons. It is widely regarded as one of the greatest television series of all time.",
    "Hidden Figures is a 2016 American biographical drama film directed by Theodore Melfi and written by Melfi and Allison Schroeder. It is based on the non-fiction book of the same name by Margot Lee Shetterly about black female mathematicians who worked at the National Aeronautics and Space Administration (NASA) during the Space Race. The film stars Taraji P. Henson as Katherine Johnson, a mathematician who calculated flight trajectories for Project Mercury and other missions. The film also features Octavia Spencer as NASA supervisor and mathematician Dorothy Vaughan and Janelle Monáe as NASA engineer Mary Jackson, with Kevin Costner, Kirsten Dunst, Jim Parsons, Glen Powell, and Mahershala Ali in supporting roles.",
    "The Office is an American television sitcom that aired on NBC from March 24, 2005, to May 16, 2013, lasting nine seasons. It is an adaptation of the original BBC series of the same name and was adapted for American television by Greg Daniels, a veteran writer for Saturday Night Live, King of the Hill, and The Simpsons. It was co-produced by Daniels's Deedle-Dee Productions, and Reveille Productions (later Shine America), in association with Universal Television. The original executive producers were Greg Daniels, Howard Klein, Ben Silverman, Ricky Gervais, and Stephen Merchant, with numerous others being promoted in later seasons. The series depicts the everyday lives of office employees in the Scranton, Pennsylvania, branch of the fictional Dunder Mifflin Paper Company. To simulate the look of an actual documentary, it was filmed in a single-camera setup, without a studio audience or a laugh track.",
    "Sex and the City is an American romantic comedy-drama television series created by Darren Star and produced by HBO. Broadcast from 1998 until 2004, the original run of the show had a total of 94 episodes. Throughout its six-year run, the show received contributions from various producers, writers, and directors, principally Michael Patrick King. Set and filmed in New York City and based on Candace Bushnell's 1997 book of the same name, the show follows the lives of a group of four women--three in their mid-thirties and one in her forties--who, despite their different natures and ever-changing sex lives, remain inseparable and confide in each other. Starring Sarah Jessica Parker (as Carrie Bradshaw), Kim Cattrall (as Samantha Jones), Kristin Davis (as Charlotte York), and Cynthia Nixon (as Miranda Hobbes), the quirky series had multiple continuing storylines that tackled relevant and modern social issues such as sexuality, safe sex, promiscuity, and femininity, while exploring the difference between friendships and romantic relationships. The deliberate omission of the better part of the early lives of the four women was the writers' way of exploring social life--from sex to relationships--through each of their four very different, individual perspectives.",
    "Manchester by the Sea is a 2016 American drama film written and directed by Kenneth Lonergan with a story by Matt Damon and John Krasinski, and starring Casey Affleck, Michelle Williams, Kyle Chandler, and Lucas Hedges. The plot follows a man after his brother dies and he is entrusted with caring for his teenage nephew. The film premiered at the Sundance Film Festival on January 23, 2016, and was soon picked up by Amazon Studios for distribution. Manchester by the Sea was filmed during March and April of 2015 in the Massachusetts town of the same name as well as Beverly, Essex, Gloucester, Swampscott, Lynn, Middleton, Tewksbury, and Salem, Massachusetts. It began a limited release on November 18, 2016, before a wide release on December 16, 2016. It grossed $79 million worldwide against an $8.5 million budget.",
    "Use an integrated toolchain for the best user and developer experience. This page describes a few popular React toolchains which help with tasks like: Scaling to many files and components. Using third-party libraries from npm. Detecting common mistakes early. Live-editing CSS and JS in development. Optimizing the output for production. The toolchains recommended on this page don’t require configuration to get started. This feature introduces a weighted scoring system for interview kits, allowing different types of questions to carry specific weights. The total score for an interview is calculated based on the defined weights and scores for each question type. This ensures a more accurate evaluation by emphasizing critical questions.",
    "The Shape of Water is a 2017 American romantic dark fantasy drama film directed by Guillermo del Toro and written by del Toro and Vanessa Taylor. It stars Sally Hawkins, Michael Shannon, Richard Jenkins, Doug Jones, Michael Stuhlbarg, and Octavia Spencer. Set in Baltimore, Maryland in 1962, the story follows a mute custodian at a high-security government laboratory who falls in love with a captured humanoid amphibian creature. Filming took place in Ontario, Canada, between August and November 2016.",
    "A specialty in medicine is a branch of medical practice. After completing medical school, physicians or surgeons usually further their medical education in a specific specialty of medicine by completing a multiple year residency to become a medical specialist.",
    "Both the role of the physician and the meaning of the word itself vary around the world. Degrees and other qualifications vary widely, but there are some common elements, such as medical ethics requiring that physicians show consideration, compassion, and benevolence for their patients.",
    "Gynecology is the medical practice dealing with the health of the female reproductive systems (vagina, uterus, and ovaries) and the breasts. Outside medicine, the term means 'the science of women'. Its counterpart is andrology, which deals with medical issues specific to the male reproductive system. Almost all modern gynaecologists are also obstetricians. In many areas, the specialities of gynaecology and obstetrics overlap. In some countries, women must first see a general practitioner prior to seeing a gynaecologist. If their condition requires training, knowledge, surgical procedure, or equipment unavailable to the GP, the patient is then referred to a gynaecologist. In the United States, however, law and many health insurance plans allow gynaecologists to provide primary care in addition to aspects of their own specialty. With this option available, some women opt to see a gynaecological surgeon for non-gynaecological problems without another physician's referral.",
    "Medical genetics is the branch of medicine that involves the diagnosis and management of hereditary disorders. Genetic medicine is a newer term for medical genetics and incorporates areas such as gene therapy, personalized medicine, and the rapidly emerging new medical specialty, predictive medicine. Medical genetics differs from human genetics in that human genetics is a field of scientific research that may or may not apply to medicine, while medical genetics refers to the application of genetics to medical care. For example, research on the causes and inheritance of genetic disorders would be considered within both human genetics and medical genetics, while the diagnosis, management, and counselling people with genetic disorders would be considered part of medical genetics. In contrast, the study of typically non-medical phenotypes such as the genetics of eye color would be considered part of human genetics, but not necessarily relevant to medical genetics (except in situations such as albinism).",
    "Traditional medicine may include formalized aspects of folk medicine, that is to say longstanding remedies passed on and practised by lay people. Folk medicine consists of the healing practices and ideas of body physiology and health preservation known to some in a culture, transmitted informally as general knowledge, and practiced or applied by anyone in the culture having prior experience. Folk medicine may also be referred to as traditional medicine, alternative medicine, indigenous medicine, or natural medicine. These terms are often considered interchangeable, even though some authors may prefer one or the other because of certain overtones they may be willing to highlight. In fact, out of these terms perhaps only indigenous medicine and traditional medicine have the same meaning as folk medicine, while the others should be understood rather in a modern or modernized context."
  ]
  const [para,setPara] = useState(examples[Math.floor(Math.random() * (examples.length - 0 + 1)) + 0]?.split(" "))
  const [val,setVal] = useState("")
  const [started,setStarted] = useState(false)
  const [ended,setEnded] = useState(false)
  const [seconds,setSeconds] = useState(60)
  const [speed,setSpeed] = useState(0)
  const [accuracy,setAccuracy] = useState(0)

  const handleChange = (e)=>{
    if(!started){
      setStarted(true)
      setTimeout(() => {
        setEnded(true)
      }, 60000)
    }
    if(e.target.value.split(" ").length===para.length+1){
      setEnded(true)
      // setSeconds(0)
    }
    setVal(e.target.value)
  }

  const handlePaste = (e)=>{
    e.preventDefault()
    alert("Copy-pasting is not allowed")
  }

  useEffect(() => {
    if (seconds === 0 || !started) return;
    const interval = setInterval(() => {
      setSeconds((prev) => prev - 1);
    }, 1000);
    return () => clearInterval(interval);
  }, [seconds,started]);

  useEffect(()=>{
    setSpeed(Math.floor(((val?.split(" ").length)/(60-seconds))*60))
    setAccuracy(()=>{
      let correct = 0
      let incorect = 0
      let words = val?.trim().split(" ")
      for(let i=0;i<words.length;i++){
        if (words[i]===para[i]){
          correct++
        }else{
          incorect++
        }
      }
      return (correct/words.length)*100
    })
    if(started)
      setSeconds(0)
  },[ended])

  return (
    <div className="App">
      <header className="App-header">
          <h2 style={{paddingTop:"0px"}}>Typing Master</h2>
          <div style={{marginBottom:"50px"}}>Remaining Time: 00:{seconds>9?seconds:`0${seconds}`}</div>
          <div style={{width:"90%",fontSize:"25px"}}>
          {para.map((i,j)=><span className={`${val.split(" ").length>j?'written':''} ${val.split(" ").length>j+1 && (val.split(" ")[j]===para[j]?'right':'wrong')}`} key={j}>{i} </span>)}
        </div>
      <textarea disabled={seconds===0} value={val} rows={5} style={{width:"90%", fontSize:"30px", marginTop:"20px", marginBottom:"50px"}} onChange={handleChange} onPaste={handlePaste}/>
      {ended && <div>
        <h2>Typing Speed: {speed} Words per minute</h2>
        <h2>Accuracy: {accuracy.toFixed(2)}%</h2>
      </div>}
      </header>
    </div>
  );
}

export default App;